// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_PadnjCv9qmo6IxesJeY-e7IDDs8qdo',
    appId: '1:1002172432729:android:8774dd093680995d4fcc48',
    messagingSenderId: '1002172432729',
    projectId: 'buzzbuddy-54ce4',
    storageBucket: 'buzzbuddy-54ce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiBS1w_79gzYXZMVQ7P-fm62HMcyX6YfQ',
    appId: '1:1002172432729:ios:ffaa649b11a6666a4fcc48',
    messagingSenderId: '1002172432729',
    projectId: 'buzzbuddy-54ce4',
    storageBucket: 'buzzbuddy-54ce4.appspot.com',
    androidClientId: '1002172432729-rk6gf0vlnisih7p6st8p6nh5cjfkt7es.apps.googleusercontent.com',
    iosClientId: '1002172432729-saj7k8kt5f9ebg5950uo35bvfllv82hv.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzBuddy',
  );
}
